//! Text rendering - pre-generated glyph atlas
//! Arabic support via offline shaping

use k1_core::{Color, Vertex, K1Result, K1Error};

/// Pre-rendered glyph in atlas
#[derive(Clone, Copy, Debug)]
pub struct Glyph {
    pub codepoint: u32,
    pub atlas_x: u16,
    pub atlas_y: u16,
    pub width: u8,
    pub height: u8,
    pub bearing_x: i8,
    pub bearing_y: i8,
    pub advance: u8,
}

/// Arabic glyph data - generated at build time
pub static ARABIC_GLYPHS: &[Glyph] = &[
    // Generated by build script using harfbuzz
    // These are placeholders - real data comes from build.rs
    Glyph { codepoint: 0x0627, atlas_x: 0, atlas_y: 0, width: 12, height: 24, bearing_x: 0, bearing_y: 18, advance: 14 }, // ا
    Glyph { codepoint: 0x0644, atlas_x: 12, atlas_y: 0, width: 16, height: 24, bearing_x: 0, bearing_y: 18, advance: 18 }, // ل
    Glyph { codepoint: 0x0633, atlas_x: 28, atlas_y: 0, width: 18, height: 24, bearing_x: 0, bearing_y: 18, advance: 20 }, // س
    // ... more glyphs
];

pub static LATIN_GLYPHS: &[Glyph] = &[
    // ASCII 32-126
    Glyph { codepoint: 0x0041, atlas_x: 0, atlas_y: 32, width: 14, height: 24, bearing_x: 0, bearing_y: 18, advance: 16 }, // A
    // ... more glyphs
];

pub struct TextRenderer {
    atlas_width: u16,
    atlas_height: u16,
}

impl TextRenderer {
    pub const fn new() -> Self {
        Self {
            atlas_width: 256,
            atlas_height: 256,
        }
    }
    
    /// Render text into vertex buffer
    pub fn render_text(
        &self,
        text: &str,
        mut x: f32,
        y: f32,
        color: Color,
        scale: f32,
        vertices: &mut [Vertex],
        vertex_count: &mut usize,
    ) -> K1Result<()> {
        let c = color.to_f32_array();
        let mut count = 0;
        
        for ch in text.chars() {
            let glyph = self.find_glyph(ch as u32)
                .ok_or(K1Error::NotSupported)?;
            
            let x0 = x + glyph.bearing_x as f32 * scale;
            let y0 = y - glyph.bearing_y as f32 * scale;
            let x1 = x0 + glyph.width as f32 * scale;
            let y1 = y0 + glyph.height as f32 * scale;
            
            let u0 = glyph.atlas_x as f32 / self.atlas_width as f32;
            let v0 = glyph.atlas_y as f32 / self.atlas_height as f32;
            let u1 = (glyph.atlas_x + glyph.width as u16) as f32 / self.atlas_width as f32;
            let v1 = (glyph.atlas_y + glyph.height as u16) as f32 / self.atlas_height as f32;
            
            let base = count;
            vertices[base + 0] = Vertex::new([x0, y0], [u0, v0], c);
            vertices[base + 1] = Vertex::new([x1, y0], [u1, v0], c);
            vertices[base + 2] = Vertex::new([x0, y1], [u0, v1], c);
            vertices[base + 3] = Vertex::new([x1, y0], [u1, v0], c);
            vertices[base + 4] = Vertex::new([x1, y1], [u1, v1], c);
            vertices[base + 5] = Vertex::new([x0, y1], [u0, v1], c);
            
            count += 6;
            x += glyph.advance as f32 * scale;
        }
        
        *vertex_count += count;
        Ok(())
    }
    
    fn find_glyph(&self, codepoint: u32) -> Option<&'static Glyph> {
        // Check Arabic range
        if (0x0600..=0x06FF).contains(&codepoint) || (0x0750..=0x077F).contains(&codepoint) {
            ARABIC_GLYPHS.iter().find(|g| g.codepoint == codepoint)
        } else {
            LATIN_GLYPHS.iter().find(|g| g.codepoint == codepoint)
        }
    }
}
